# Generated by Django 5.1.3 on 2024-12-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsesoriaLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreServicio', models.CharField(max_length=255)),
                ('descripcionServicio', models.TextField()),
                ('_costoServicio', models.IntegerField()),
                ('especialidad', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Divorcio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreServicio', models.CharField(max_length=255)),
                ('descripcionServicio', models.TextField()),
                ('_costoServicio', models.IntegerField()),
                ('duracion', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
