# Generated by Django 5.1.3 on 2024-11-21 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreServicio', models.CharField(max_length=255)),
                ('descripcionServicio', models.TextField()),
                ('costoServicio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AsesoriaLegal',
            fields=[
                ('serviciolegal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.serviciolegal')),
                ('especialidad', models.CharField(max_length=255)),
            ],
            bases=('usuarios.serviciolegal',),
        ),
        migrations.CreateModel(
            name='Divorcio',
            fields=[
                ('serviciolegal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.serviciolegal')),
                ('duracion', models.CharField(max_length=255)),
            ],
            bases=('usuarios.serviciolegal',),
        ),
    ]
