# Generated by Django 5.1.3 on 2024-11-13 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Casos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoCaso', models.CharField(max_length=255)),
                ('Descripcion', models.TextField()),
                ('Fk_abogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.abogados')),
                ('Fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
